version: '3'
networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
services:
  unbound:
    image: 'mvance/unbound:latest'
    container_name: unbound
    restart: unless-stopped
    hostname: unbound
    volumes:
      - './unbound:/opt/unbound/etc/unbound/'
    networks:
      private_network:
        ipv4_address: 10.2.0.200
  wireguard:
    depends_on:
      - unbound
      - adguard
    image: 'ghcr.io/wg-easy/wg-easy:15'
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=10.2.0.100
      - INTERNAL_SUBNET=10.6.0.0
    volumes:
      - './wireguard:/config'
      - '/lib/modules:/lib/modules'
    ports:
      - '51820:51820/udp'
      - '51821:51821/tcp'
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    restart: unless-stopped
    networks:
      private_network:
        ipv4_address: 10.2.0.3
  adguard:
    depends_on:
      - unbound
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    volumes:
      - './adguard/opt-adguard-work:/opt/adguardhome/work'
      - './adguard/opt-adguard-conf:/opt/adguardhome/conf'
    networks:
      private_network:
        ipv4_address: 10.2.0.100
